### PR TITLE
Fixed bug that prevented collection of latency metrics

### PR DESCRIPTION
**Pull request by jaloren**
Because of how the consul node name was matched, a match was never found and thus latency metrics were never collected.

On consul integration version 2.0.0, the following error is logged:

[ERR] Error collecting latency metrics for Agent '192.168.40.233:8301': could not find node for agent

The problem is that the entity name is a combination of the consul
address and port number, while the actual consul node name is not. Its
usually the FQDN but it does not have to be. Its extremely unlike to be
an IP and its not going to have a port number in it.

To fix this problem, the code for finding a node and returning its
api.Coordinate struct was modified to get the consul name from the
entity's ID Attributes.

I also added go.mod to enable module support so that people who are
runing in that mode can easily work and submit changes to this repo.

#### Description of the changes

Add a detailed description and purpose of your changes.
Link the issue it solves (if there is one).

### Author

- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [ ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by ccheek21** [comment]
Hi @jaloren -- thanks for the PR! Taking a look at this now

**Comment by ccheek21** [comment]
@jaloren I pulled the changes into the branch `bugfix/metric-latency` and made a few changes. Would you mind taking a look and making sure it still fixes your issue?

**Comment by jaloren** [comment]
@ccheek21 That does fix my problem thanks. I noticed that go.mod was removed in your change set.

If I open a separate PR just to add go.mod and go.sum to the repo, would you consider merging that separately?

**Comment by ccheek21** [comment]
@jaloren Glad to hear it still works for you!

As far as adding `go.mod`, currently we use `govendor` for all our integrations. At some point we might move to modules, but we would like the dependency management to be consistent across all integrations. We'll have to address that in a more broad fashion (including updating all the build tools) with some more planning. So, right now I don't think we'd be able to merge a PR that adds those. Thank you for the offer though!

**Pull request merged**
