### PR TITLE
Leader reporting localhost

### PR DESCRIPTION
**Pull request by varas**
#### Description of the changes

Apparently Consul leader may report their address as 127.0.0.1, tried this using docker image  `consul:1.5.2`.

In this case subsequent datacenter request will fail with this output:

```
{"name":"com.newrelic.consul","protocol_version":"3","integration_version":"2.1.0","data":[{"entity":{"name":"127.0.0.1:8301","type":"co-agent","id_attributes":[{"Key":"co-agent","Value":"consul-deployment-5d76495c89-x54qg"}]},"metrics":[{"datacenter":"dc1","displayName":"127.0.0.1:8301","entityName":"co-agent:127.0.0.1:8301","event_type":"ConsulAgentSample","ip":"127.0.0.1"}],"inventory":{},"events":[]}]}
[ERR] Error creating Datacenter entity: Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
[ERR] Error retrieving self configuration data for Agent '127.0.0.1:8301': Get http://127.0.0.1:8500/v1/agent/self: dial tcp 127.0.0.1:8500: getsockopt: connection refused
[ERR] Error collecting core metrics for Agent '127.0.0.1:8301': Get http://127.0.0.1:8500/v1/agent/metrics: dial tcp 127.0.0.1:8500: getsockopt: connection refused
[ERR] Error collecting peer count for Agent '127.0.0.1:8301': Get http://127.0.0.1:8500/v1/status/peers: dial tcp 127.0.0.1:8500: getsockopt: connection refused
[ERR] Error collecting latency metrics for Agent '127.0.0.1:8301': Get http://127.0.0.1:8500/v1/coordinate/nodes: dial tcp 127.0.0.1:8500: getsockopt: connection refused
```

There are no changes here, just surfacing the issue.

### Author

- [x] the PR should focus on a single subject. Change only relevant files to the problem you’re working on
Clean and format the code
- [ ] add unit tests for your changes and make sure all unit tests are passing
- [ ] add a risk label after carefully considering the "blast radius" of your changes
- [ ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ ] assign at least one reviewer
- [ ] address the feedback 

### Reviewer

- [ ] review code for readability
- [ ] verify that high risk behavior changes are well tested
- [ ] check license for any new external dependency
- [ ] ask questions about anything that isn't clear and obvious
- [ ] approve the PR when you consider it's good to merge

### CODE REVIEW

**Comment by camdencheek** [comment]
@varas Thanks for the PR. I'm a little confused -- there don't seem to be any code changes here. Is theis still an issue? Or were the tests failing on that env?

**Comment by varas** [comment]
Indeed there are no changes here, I'm just surfacing the issue with a failing test, besides looks like there's no CI build.

This is still an issue.

**Comment by camdencheek** [comment]
@varas This appears to be a configuration issue. My guess is that the member isn't configured correctly to advertise its cluster address. I've copied the relevant portio of the docker image docs:

```
Since Consul is almost always run with --net=host in Docker, some care is required when configuring Consul's IP addresses. Consul has the concept of its cluster address as well as its client address. The cluster address is the address at which other Consul agents may contact a given agent. The client address is the address where other processes on the host contact Consul in order to make HTTP or DNS requests. You will typically need to tell Consul what its cluster address is when starting so that it binds to the correct interface and advertises a workable interface to the rest of the Consul agents. You'll see this in the examples below as the -bind=<external ip> argument to Consul.
```

**Comment by varas** [comment]
Oh! didn't know that, closing.

**Comment by varas** [comment]
Btw it'd be interesting for the integration to trigger a warning "event" in case it detects a node reporting itself as localhost.

**Comment by camdencheek** [comment]
That's a good idea. I'll add a log message in that case to help customers running into this

**Pull request closed without merging**
